//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorZnakUA.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DorZnakUA.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутрішня помилка сервера.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не валідний токен.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недійсний запит клієнта.
        /// </summary>
        internal static string InvslidClientRequest {
            get {
                return ResourceManager.GetString("InvslidClientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стійка з такою назвою вже існує.
        /// </summary>
        internal static string MetalRackAlreadyExists {
            get {
                return ResourceManager.GetString("MetalRackAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Металева стійка не знайдена.
        /// </summary>
        internal static string MetalRackNotFound {
            get {
                return ResourceManager.GetString("MetalRackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Металеві стійки не знайдено.
        /// </summary>
        internal static string MetalRacksNotFound {
            get {
                return ResourceManager.GetString("MetalRacksNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Металева стійка зі схожими параметрами вже існує.
        /// </summary>
        internal static string MetalRackWithSimilarParametersAlreadyExists {
            get {
                return ResourceManager.GetString("MetalRackWithSimilarParametersAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вірний пароль.
        /// </summary>
        internal static string PasswordIsWrong {
            get {
                return ResourceManager.GetString("PasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірочний пароль не відповідає основному паролю.
        /// </summary>
        internal static string PasswordNotEqualsPasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordNotEqualsPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проєкт з такою назвою вже існує.
        /// </summary>
        internal static string ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проєкт не знайдено.
        /// </summary>
        internal static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проєкти не знайдені.
        /// </summary>
        internal static string ProjectsNotFound {
            get {
                return ResourceManager.GetString("ProjectsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося зареєструватися.
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорожній знак вже має цей щит.
        /// </summary>
        internal static string RoadSignAlreadyHasThisShield {
            get {
                return ResourceManager.GetString("RoadSignAlreadyHasThisShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорожній знак не знайдено.
        /// </summary>
        internal static string RoadSignNotFound {
            get {
                return ResourceManager.GetString("RoadSignNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорожні знаки не знайдено.
        /// </summary>
        internal static string RoadSignsNotFound {
            get {
                return ResourceManager.GetString("RoadSignsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль з такою назвою вже існує.
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль не знайдено.
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щит вже існує.
        /// </summary>
        internal static string ShieldAlreadyExists {
            get {
                return ResourceManager.GetString("ShieldAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щит не знайдено.
        /// </summary>
        internal static string ShieldNotFound {
            get {
                return ResourceManager.GetString("ShieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щити не знайдено.
        /// </summary>
        internal static string ShieldsNotFound {
            get {
                return ResourceManager.GetString("ShieldsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з таким логіном вже існує.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з такою роллю вже існує.
        /// </summary>
        internal static string UserAlreadyExistsThisRole {
            get {
                return ResourceManager.GetString("UserAlreadyExistsThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Користувач не був знайдений.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такий вітровий район вже існує.
        /// </summary>
        internal static string WindZoneAlreadyExists {
            get {
                return ResourceManager.GetString("WindZoneAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітрову зону не знайдено.
        /// </summary>
        internal static string WindZoneNotFound {
            get {
                return ResourceManager.GetString("WindZoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жодного вітрового району не знайдено.
        /// </summary>
        internal static string WindZonesNotFound {
            get {
                return ResourceManager.GetString("WindZonesNotFound", resourceCulture);
            }
        }
    }
}
